storage:
  image: siptg/storage
  restart: always
  net: host
  mem_limit: 512m
  volumes:
    - ./storage/settings.json:/root/settings.json:ro
    - ./storage/sessions:/root/sessions
    - ./storage/storage.log:/root/storage.log

nginx:
  image: nginx
  restart: always
  net: host
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./ssl:/etc/nginx/ssl:ro
